In [2]:
import pandas as pd
! ls *timeline*

aggregate_timeline_data.csv  timelineplot.ipynb

In [11]:
tf=pd.read_csv('aggregate_timeline_data.csv')

tf.Time=[x.replace('Jan ','1/1/').replace('Jul ','7/1/') for x in tf.Time.values]

tf

,Time,A/swine/Shandong/1207/2016,A/Ohio/13/2017,A/Indiana/08/2011,A/canine/Illinois/12191/2015
0,1/1/2018,0.032781,0.033915,0.038416,0.080415
1,7/1/2018,0.031051,0.029356,0.040984,0.064843
2,1/1/2019,0.044415,0.035359,0.038860,0.060634
3,7/1/2019,0.037899,0.030091,0.049837,0.053959
4,1/1/2020,0.028677,0.030730,0.046689,0.059856
5,7/1/2020,0.034183,0.032315,0.053221,0.062654
6,1/1/2021,0.058453,0.032501,0.049033,0.064146
7,7/1/2021,0.069476,0.030599,0.041815,0.065595
8,1/1/2022,0.045593,0.038551,0.050595,0.063619
9,7/1/2022,0.046865,0.048670,0.069439,0.068311