# Make Tables for Paper

In [7]:
import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from zedstat.textable import textable

In [8]:
DATA_DIR = 'results/enet_who_comparison/'
OUT_DIR = 'tables/'
FILES = ['north_h1n1', 'south_h1n1', 'north_h3n2', 'south_h3n2']

NORTH_YEARS = []
for i in np.arange(3, 24):
    YEAR = ''
    if i < 10:
        YEAR += '200' + str(i)
    else:
        YEAR += ('20' + str(i))
    if i + 1 < 10:
        YEAR += '-0' + str(i + 1)
    else:
        YEAR += '-' + str(i + 1)
    NORTH_YEARS.append(YEAR)
        
SOUTH_YEARS = []
for i in np.arange(3, 24):
    if i < 10:
        SOUTH_YEARS.append('200' + str(i))
    else:
        SOUTH_YEARS.append('20' + str(i))

## Enet vs. WHO Recommendations

In [9]:
dfs = []
for FILE in FILES:
    df = pd.read_csv(DATA_DIR + FILE + '.csv')
    df = df[['name_who','name_0','name_1','ha_who_error','ha_enet_error','na_who_error','na_enet_error']]
    if FILE[:5] == 'north':
        df['Season'] = NORTH_YEARS
    else:
        df['Season'] = SOUTH_YEARS
    df = df.set_index('Season')
    df = df.rename(columns={'name_who':'WHO Recommendation',
                            'name_0':'Emergenet Recommendation 1',
                            'name_1':'Emergenet Recommendation 2',
                            'ha_who_error':'Avg. HA WHO Error',
                            'ha_enet_error':'Avg. HA Enet Error',
                            'na_who_error':'Avg. NA WHO Error',
                            'na_enet_error':'Avg. NA Enet Error'})
    dfs.append(df)
#     textable(df, tabname = OUT_DIR + FILE + '.tex', FORMAT='%1.1f')

In [10]:
dfs[0].round(2)

,WHO Recommendation,Emergenet Recommendation 1,Emergenet Recommendation 2,Avg. HA WHO Error,Avg. HA Enet Error,Avg. NA WHO Error,Avg. NA Enet Error
Season,,,,,,,
2003-04,A/New Caledonia/20/99,A/HaNoi/2143/2001,A/New York/291/2002,7.26,2.89,3.79,4.79
2004-05,A/New Caledonia/20/99,A/HaNoi/2546/2002,A/HaNoi/2476/2001,10.12,8.50,4.38,4.38
2005-06,A/New Caledonia/20/99,A/HaNoi/2253/2001,A/HaNoi/2253/2001,7.26,5.26,4.60,4.60
2006-07,A/New Caledonia/20/99,A/Malaysia/25531/2003,A/Yazd/144/2006,9.62,6.13,5.85,3.86
2007-08,A/Solomon Islands/3/2006,A/New York/1050/2006,A/Canterbury/106/2004,10.23,3.99,14.49,5.65
2008-09,A/Brisbane/59/2007,A/England/545/2007,A/Illinois/UR006-018/2007,5.66,4.64,4.53,5.48
2009-10,A/Brisbane/59/2007,A/England/557/2007,A/Peru/3909/2008,112.36,111.30,83.96,82.90
2010-11,A/California/7/2009,A/Taiwan/97196/2009,A/Bogota/WRAIR0088N/2009,5.51,3.21,2.38,0.14
2011-12,A/California/7/2009,A/Ayutthaya/568/2009,A/Korea/94/2009,7.50,3.51,4.10,3.11
2012-13,A/California/7/2009,A/Kenya/Kilifi-011/2010,A/Taiwan/66169/2010,11.29,4.31,4.69,1.37
2013-14,A/California/7/2009,A/IIV-Vladimir/67/2011,A/American_Samoa/4520/2011,11.82,2.48,8.02,3.14
2014-15,A/California/7/2009,A/Cruz Alta/LACENRS-129/2012,A/Cluj/133922/2013,16.11,4.84,12.80,6.20
2015-16,A/California/7/2009,A/Laos/I018/2014,A/USA/VFFSP_UNITHER_00011/2014,15.34,5.37,13.79,7.00
2016-17,A/California/7/2009,A/Lebanon/1104/2016,A/Slovenia/1413/15,16.19,1.74,14.12,1.46
2017-18,A/Michigan/45/2015,A/Panama/317744/2016,A/Sweden/39/2015,4.41,3.41,4.04,4.04
2018-19,A/Michigan/45/2015,A/Clermont-Ferrand/1873/2017,A/Mississippi/09/2018,6.15,2.15,5.07,1.09
2019-20,A/Brisbane/02/2018,A/Michigan/200/2018,A/Maryland/12/2019,8.40,6.40,4.90,5.90
2020-21,A/Guangdong-Maonan/SWL1536/2019,A/Mauritius/I-609/2019,A/Guyane/1882/2019,5.09,5.74,3.60,3.50
2021-22,A/Victoria/2570/2019,A/Washington/16/2020,A/Nordrhein-Westfalen/7/2020,9.87,4.77,2.28,2.63
2022-23,A/Victoria/2570/2019,A/Netherlands/00475/2020,A/Bangladesh/9004/2021,10.53,4.52,1.27,1.46
2023-24,A/Victoria/4897/2022,A/Valladolid/18/2023,A/South_Africa/R05753/2022,-1.00,-1.00,-1.00,-1.00

## Enet Improvement Table

In [20]:
subtype = 2*(['H1N1']*3 + ['H3N2']*3)
gene = 6*['HA'] + 6*['NA']
hemisphere = 4*['North', 'South', 'Average']

who_err_20 = [] # 2 decade error
enet_err_20 = [] 
who_err_10 = [] # 1 decade error
enet_err_10 = [] 
who_err_15_19 = [] # 2015-2019 error
enet_err_15_19 = [] 

for SEGMENT in ['ha', 'na']:
    for i in range(0, 4, 2):
        north_df = pd.read_csv(DATA_DIR + FILES[i] + '.csv')[:-1]
        south_df = pd.read_csv(DATA_DIR + FILES[i + 1] + '.csv')[:-1]
        WHO = SEGMENT + '_who_error'
        ENET = SEGMENT + '_enet_error'
        # WHO north
        who_err_20.append(np.mean(north_df[WHO]))
        who_err_10.append(np.mean(north_df[WHO][-10:]))
        who_err_15_19.append(np.mean(north_df[WHO][12:17]))
        # Enet north
        enet_err_20.append(np.mean(north_df[ENET]))
        enet_err_10.append(np.mean(north_df[ENET][-10:]))
        enet_err_15_19.append(np.mean(north_df[ENET][12:17]))
        # WHO south
        who_err_20.append(np.mean(south_df[WHO]))
        who_err_10.append(np.mean(south_df[WHO][-10:]))
        who_err_15_19.append(np.mean(south_df[WHO][12:17]))
        # Enet south
        enet_err_20.append(np.mean(south_df[ENET]))
        enet_err_10.append(np.mean(south_df[ENET][-10:]))
        enet_err_15_19.append(np.mean(south_df[ENET][12:17]))
        # WHO average
        who_err_20.append(np.mean(who_err_20[-2:]))
        who_err_10.append(np.mean(who_err_10[-2:]))
        who_err_15_19.append(np.mean(who_err_15_19[-2:]))
        # Enet average
        enet_err_20.append(np.mean(enet_err_20[-2:]))
        enet_err_10.append(np.mean(enet_err_10[-2:]))
        enet_err_15_19.append(np.mean(enet_err_15_19[-2:]))

improvement_20 = 100 * (np.array(who_err_20) - np.array(enet_err_20)) / np.array(enet_err_20)
improvement_10 = 100 * (np.array(who_err_10) - np.array(enet_err_10)) / np.array(enet_err_10)
improvement_15_19 = 100 * (np.array(who_err_15_19) - np.array(enet_err_15_19)) / np.array(enet_err_15_19)

enet_improvement = pd.DataFrame({'Subtype':subtype,
                                 'Gene':gene,
                                 'Hemisphere':hemisphere,
                                 'WHO Error (2 decade)':who_err_20,
                                 'Enet Error (2 decade)':enet_err_20,
                                 'Improvement (2 decade) (%)':improvement_20,
                                 'WHO Error (1 decade)':who_err_10,
                                 'Enet Error (1 decade)':enet_err_10,
                                 'Improvement (1 decade) (%)':improvement_10,
                                 'WHO Error (2015-2019)':who_err_15_19,
                                 'Enet Error (2015-2019)':enet_err_15_19,
                                 'Improvement (2015-2019) (%)':improvement_15_19})
enet_improvement.to_csv(DATA_DIR + 'enet_improvement.csv', index=False)

In [21]:
enet_improvement = pd.read_csv(DATA_DIR + 'enet_improvement.csv', index_col=0)
# textable(enet_improvement, tabname = OUT_DIR + 'enet_improvement.tex', FORMAT='%1.2f')
enet_improvement.round(2)

,Gene,Hemisphere,WHO Error (2 decade),Enet Error (2 decade),Improvement (2 decade) (%),WHO Error (1 decade),Enet Error (1 decade),Improvement (1 decade) (%),WHO Error (2015-2019),Enet Error (2015-2019),Improvement (2015-2019) (%)
Subtype,,,,,,,,,,,
H1N1,HA,North,14.54,9.76,48.97,10.39,4.14,150.88,10.10,3.81,164.67
H1N1,HA,South,13.67,8.70,57.17,10.28,4.02,155.83,9.69,3.80,154.71
H1N1,HA,Average,14.10,9.23,52.83,10.34,4.08,153.32,9.89,3.81,159.70
H3N2,HA,North,9.10,5.53,64.58,8.76,6.40,36.74,8.08,5.94,35.97
H3N2,HA,South,8.51,4.83,76.38,8.11,5.16,57.19,7.27,4.08,77.94
H3N2,HA,Average,8.81,5.18,70.08,8.43,5.78,45.86,7.68,5.01,53.06
H1N1,NaN,North,10.13,7.64,32.70,6.99,3.64,91.83,8.38,3.90,114.97
H1N1,NaN,South,10.20,7.48,36.29,6.73,3.72,81.20,7.80,4.30,81.35
H1N1,NaN,Average,10.16,7.56,34.48,6.86,3.68,86.46,8.09,4.10,97.34
H3N2,NaN,North,5.36,3.56,50.80,5.52,3.40,62.15,7.15,4.58,56.15
H3N2,NaN,South,5.46,3.56,53.45,5.17,3.47,48.87,6.48,4.16,55.58
H3N2,NaN,Average,5.41,3.56,52.13,5.35,3.44,55.44,6.82,4.37,55.88

## Random Enet Improvement Table

In [22]:
subtype = 2*(['H1N1']*3 + ['H3N2']*3)
gene = 6*['HA'] + 6*['NA']
hemisphere = 4*['North', 'South', 'Average']

random_err_20 = [] # 2 decade error
enet_err_20 = [] 
random_err_10 = [] # 1 decade error
enet_err_10 = []

for SEGMENT in ['ha', 'na']:
    for i in range(0, 4, 2):
        north_df = pd.read_csv(DATA_DIR + FILES[i] + '_random.csv')[:-1]
        south_df = pd.read_csv(DATA_DIR + FILES[i + 1] + '_random.csv')[:-1]
        RANDOM = SEGMENT + '_random_error_95'
        ENET = SEGMENT + '_enet_error'
        # RANDOM north
        random_err_20.append(np.mean(north_df[RANDOM]))
        random_err_10.append(np.mean(north_df[RANDOM][-10:]))
        # Enet north
        enet_err_20.append(np.mean(north_df[ENET]))
        enet_err_10.append(np.mean(north_df[ENET][-10:]))
        # RANDOM south
        random_err_20.append(np.mean(south_df[RANDOM]))
        random_err_10.append(np.mean(south_df[RANDOM][-10:]))
        # Enet south
        enet_err_20.append(np.mean(south_df[ENET]))
        enet_err_10.append(np.mean(south_df[ENET][-10:]))
        # RANDOM average
        random_err_20.append(np.mean(random_err_20[-2:]))
        random_err_10.append(np.mean(random_err_10[-2:]))
        # Enet average
        enet_err_20.append(np.mean(enet_err_20[-2:]))
        enet_err_10.append(np.mean(enet_err_10[-2:]))

improvement_20 = 100 * (np.array(random_err_20) - np.array(enet_err_20)) / np.array(enet_err_20)
improvement_10 = 100 * (np.array(random_err_10) - np.array(enet_err_10)) / np.array(enet_err_10)

enet_improvement = pd.DataFrame({'Subtype':subtype,
                                 'Gene':gene,
                                 'Hemisphere':hemisphere,
                                 'Random Error (2 decade)':random_err_20,
                                 'Enet Error (2 decade)':enet_err_20,
                                 'Improvement (2 decade) (%)':improvement_20,
                                 'Random Error (1 decade)':random_err_10,
                                 'Enet Error (1 decade)':enet_err_10,
                                 'Improvement (1 decade) (%)':improvement_10})
enet_improvement.to_csv(DATA_DIR + 'enet_improvement_random.csv', index=False)

In [23]:
enet_improvement = pd.read_csv(DATA_DIR + 'enet_improvement_random.csv', index_col=0)
# textable(enet_improvement, tabname = OUT_DIR + 'enet_improvement_random.tex', FORMAT='%1.2f')
enet_improvement.round(2)

,Gene,Hemisphere,Random Error (2 decade),Enet Error (2 decade),Improvement (2 decade) (%),Random Error (1 decade),Enet Error (1 decade),Improvement (1 decade) (%)
Subtype,,,,,,,,
H1N1,HA,North,12.04,9.76,23.37,7.00,4.14,68.89
H1N1,HA,South,12.81,8.70,47.36,6.72,4.02,67.23
H1N1,HA,Average,12.43,9.23,34.67,6.86,4.08,68.07
H3N2,HA,North,8.82,5.53,59.56,10.12,6.40,58.01
H3N2,HA,South,8.45,4.83,75.14,9.30,5.16,80.27
H3N2,HA,Average,8.64,5.18,66.82,9.71,5.78,67.95
H1N1,NaN,North,8.79,7.64,15.08,4.71,3.64,29.26
H1N1,NaN,South,9.84,7.48,31.54,4.85,3.72,30.40
H1N1,NaN,Average,9.31,7.56,23.23,4.78,3.68,29.84
H3N2,NaN,North,4.59,3.56,29.03,4.50,3.40,32.05
H3N2,NaN,South,5.16,3.56,44.80,4.72,3.47,36.00
H3N2,NaN,Average,4.87,3.56,36.92,4.61,3.44,34.05